
import edu.smu.tspell.wordnet.*;
import disambclasses.Disambiguate;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisambiuateMenu.java
 *
 * Created on 23-Mar-2011, 18:15:53
 */

/**
 *
 * @author HOME
 */
public class DisambiuateMenu extends javax.swing.JFrame {

    /** Creates new form DisambiuateMenu */
    public DisambiuateMenu() {
         String wnpath = "";
        if (System.getProperty("os.name").contains("Windows"))
            wnpath = ".\\libs\\WordNet-3.0\\dict\\";
        else
            wnpath = "./libs/WordNet-3.0/dict/";
        System.setProperty("wordnet.database.dir", wnpath);
       // System.setProperty("wordnet.database.dir", ".\\libs\\WordNet-3.0\\dict\\");
      //  System.setProperty("wordnet.database.dir", "./libs/WordNet-3.0/dict/");
        initComponents();
        //TextTargetWord.setText("line");
        //TextAreaText.setText("line of people store");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TextTargetWord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonGo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaDef = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        RadioButtonNoun = new javax.swing.JRadioButton();
        RadioButtonAdj = new javax.swing.JRadioButton();
        RadioButtonVerb = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextTargetWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTargetWordActionPerformed(evt);
            }
        });

        TextAreaText.setColumns(20);
        TextAreaText.setLineWrap(true);
        TextAreaText.setRows(5);
        TextAreaText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TextAreaText);

        jLabel1.setText("Cuvantul de dezambiguizat:");

        jLabel2.setText("Din textul:");

        ButtonGo.setText("Dezambiguizeaza-ma!");
        ButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGoActionPerformed(evt);
            }
        });

        TextAreaDef.setColumns(20);
        TextAreaDef.setLineWrap(true);
        TextAreaDef.setRows(5);
        TextAreaDef.setWrapStyleWord(true);
        TextAreaDef.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextAreaDef.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextAreaDef.setEnabled(false);
        TextAreaDef.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(TextAreaDef);

        jLabel3.setText("Definitia probabila:");

        buttonGroup1.add(RadioButtonNoun);
        RadioButtonNoun.setSelected(true);
        RadioButtonNoun.setText("substantiv");
        RadioButtonNoun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNounActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonAdj);
        RadioButtonAdj.setText("adjectiv");

        buttonGroup1.add(RadioButtonVerb);
        RadioButtonVerb.setText("verb");
        RadioButtonVerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonVerbActionPerformed(evt);
            }
        });

        jLabel4.setText("Partea de vorbire:");

        jLabel5.setText("Dimensiunea ferestrei:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "7", "11" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonVerb)
                    .addComponent(ButtonGo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addComponent(TextTargetWord, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonNoun)
                            .addComponent(RadioButtonAdj))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextTargetWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonNoun)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonAdj)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonVerb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(ButtonGo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextTargetWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTargetWordActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_TextTargetWordActionPerformed

    private void ButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGoActionPerformed
        // TODO add your handling code here:

        String raport = "raportDezambiguizare.txt";
        String diverse = "dateDiverse.txt";

        String word = TextTargetWord.getText();
        String text = TextAreaText.getText();
        SynsetType pos = null;
        if (RadioButtonNoun.isSelected())
            pos = SynsetType.NOUN;
        if (RadioButtonAdj.isSelected())
            pos = SynsetType.ADJECTIVE;
        if (RadioButtonVerb.isSelected())
            pos = SynsetType.VERB;
        int windowSize = Integer.valueOf(jComboBox1.getSelectedItem().toString());
       
        Disambiguate d = new Disambiguate(diverse, raport);
        d.setParameters(word, pos, text, windowSize);
        d.disambiguate();
        String definition = d.getSenseDef();
        if (definition == null) definition = " - cuvantul nu exista in baza de date sau nu a fost gasit in contextul dat - ";
        else
            definition = d.getSenseWordForms() + "\n = " + definition;
        TextAreaDef.setText(definition);
        TextAreaDef.setCaretPosition(0);

   /*     d.buildWordList(text, word, windowSize);
        String[] window = d.windowWords;
        if (window!=null)
        for (String s : window)
            System.out.println(s + " ");  */
    }//GEN-LAST:event_ButtonGoActionPerformed

    private void RadioButtonNounActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNounActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonNounActionPerformed

    private void RadioButtonVerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonVerbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonVerbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisambiuateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGo;
    private javax.swing.JRadioButton RadioButtonAdj;
    private javax.swing.JRadioButton RadioButtonNoun;
    private javax.swing.JRadioButton RadioButtonVerb;
    private javax.swing.JTextArea TextAreaDef;
    private javax.swing.JTextArea TextAreaText;
    private javax.swing.JTextField TextTargetWord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
